### PR TITLE
Favor mvn exec rather than java jar

### PR DESCRIPTION
**Pull request by cricket007**
# stream-registry PR

Manual invocation of `java jar` could potentially have classpath issues and stale artifacts can exist under `assembly/target`. Using Maven to run the main class, we are guaranteed for everything to be accurate. 

### Added
* `exec-maven-plugin`

### Changed
* `Makefile` run and debug targets

# PR Checklist Forms

- [ ] CHANGELOG.md updated
- [x] Reviewer assigned
- [x] PR assigned (presumably to submitter)
- [x] Labels added (enhancement, bug, documentation)

### CODE REVIEW

**Comment by cricket007** [comment]
Do we really need to update changelogs for non-deployed code changes? E.g Makefile and documentation changes that aren't "modifying core behavior" ?

**Comment by neoword** [comment]
We've been talking about high level changes in CHANGELOG for documentation.
Simple typos are probably overkill.
That being said, this functionality might merit a CHANGELOG:

### Changed
- Preferring `exec-maven-plugin` over jar to ensure proper dependencies.

**Comment by neoword** [comment]
Looks like this PR has caused some instability in `make run` ... can we revert please ?

**Comment by neoword** [comment]
Reverting until we figure out why we are getting certain classpath issues on `make run`

**Pull request merged**
