### PR TITLE
package name cleanup

### LINKED ISSUE #16: package name cleanup
Desired Behavior
==============================

Renamed Java packages to reflect that this is the Stream Registry, which is a component of the Streaming Platform

Benefits
==============================

### PR DESCRIPTION
**Pull request by nathanwalther**
# stream-registry PR

Renamed Java packages to reflect that this is the Stream Registry, which is a component of the Streaming Platform. Fixes #16.

### Changed
* Java packages from `com.homeaway.streamingplatform` to `com.homeaway.streamingplatform.streamregistry`.

# PR Checklist Forms

- [x] CHANGELOG.md updated
- [x] Reviewer assigned
- [x] PR assigned (presumably to submitter)
- [x] Labels added (enhancement, bug, documentation)

### CODE REVIEW

**Comment by neoword** [comment]
@cricket007 the reason for streamingplatform is there will be other major components of the streaming platform not related to stream registry.

**Comment by cricket007** [comment]
Such as?

**Comment by nathanwalther** [comment]
Instead changing to `com.homeaway.streamplatform.streamregistry` per conversation with @neoword.

**Comment by neoword** [comment]
Can you resolve conflicts ?

**Pull request merged**
